export type AIToolCategory =
  | 'AI写作'
  | 'AI图像'
  | 'AI视频'
  | 'AI办公'
  | 'AI聊天'
  | 'AI智能体'
  | 'AI编程'
  | 'AI设计'
  | 'AI音频'
  | 'AI搜索'
  | 'AI开发平台'

export type AIToolPricing = '免费' | '免费试用' | '付费' | '开源'

export interface AIToolItem {
  id: string
  name: string
  description: string
  category: AIToolCategory
  tags: string[]
  url: string
  rating: number
  pricing: AIToolPricing
  chinaReady: boolean
  hot?: boolean
  latest?: boolean
  business?: boolean
  scenario: string
}

export const AI_TOOL_CATEGORIES: Array<'全部' | AIToolCategory> = [
  '全部',
  'AI写作',
  'AI图像',
  'AI视频',
  'AI办公',
  'AI聊天',
  'AI智能体',
  'AI编程',
  'AI设计',
  'AI音频',
  'AI搜索',
  'AI开发平台',
]

export const AI_TOOLS_CATALOG: AIToolItem[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: '通用 AI 助手，适合问答、写作、分析、代码和多模态任务。',
    category: 'AI聊天',
    tags: ['通用助手', '多模态', '写作', '代码'],
    url: 'https://chatgpt.com/',
    rating: 98,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '企业员工日常问答、内容草稿、方案梳理',
  },
  {
    id: 'claude',
    name: 'Claude',
    description: '长文本理解和复杂推理能力强，适合文档、代码和严肃写作。',
    category: 'AI聊天',
    tags: ['长文本', '推理', '写作', '代码'],
    url: 'https://claude.ai/',
    rating: 96,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '合同阅读、长文档分析、复杂任务拆解',
  },
  {
    id: 'doubao',
    name: '豆包',
    description: '字节跳动推出的全能 AI 助手，覆盖聊天、写作、图片等场景。',
    category: 'AI聊天',
    tags: ['国内可用', '通用助手', '写作', '图片'],
    url: 'https://www.doubao.com/',
    rating: 94,
    pricing: '免费',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '国内团队日常创作、办公问答、内容生成',
  },
  {
    id: 'kimi',
    name: 'Kimi',
    description: '擅长长文本阅读、网页总结和资料整理的中文 AI 助手。',
    category: 'AI聊天',
    tags: ['国内可用', '长文本', '资料整理'],
    url: 'https://kimi.moonshot.cn/',
    rating: 92,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '资料阅读、会议材料整理、行业信息摘要',
  },
  {
    id: 'qwen',
    name: '通义千问',
    description: '阿里推出的通用大模型助手，适合办公、写作和代码辅助。',
    category: 'AI聊天',
    tags: ['国内可用', '办公', '代码', '写作'],
    url: 'https://tongyi.aliyun.com/qianwen/',
    rating: 91,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '中文办公、数据理解、内容生成',
  },
  {
    id: 'metaso',
    name: '秘塔 AI 搜索',
    description: '面向中文场景的 AI 搜索引擎，适合资料查找和结果总结。',
    category: 'AI搜索',
    tags: ['国内可用', '搜索', '资料', '总结'],
    url: 'https://metaso.cn/',
    rating: 93,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '竞品调研、行业资料搜索、选题研究',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: '带引用来源的 AI 搜索工具，适合快速获取英文资料和研究线索。',
    category: 'AI搜索',
    tags: ['搜索', '引用', '研究', '英文资料'],
    url: 'https://www.perplexity.ai/',
    rating: 95,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '海外资料搜索、市场研究、事实核验',
  },
  {
    id: 'you',
    name: 'You.com',
    description: 'AI 搜索和多模型问答平台，适合搜索、总结和研究。',
    category: 'AI搜索',
    tags: ['搜索', '多模型', '研究'],
    url: 'https://you.com/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '海外信息检索、多来源问答',
  },
  {
    id: 'tiangong',
    name: '天工 AI',
    description: '中文 AI 助手和搜索工具，覆盖问答、写作和资料整理。',
    category: 'AI搜索',
    tags: ['国内可用', '搜索', '写作'],
    url: 'https://www.tiangong.cn/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '中文资料搜索、内容创作辅助',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: '高质量 AI 图像生成工具，适合创意视觉、海报和概念图。',
    category: 'AI图像',
    tags: ['生图', '海报', '概念设计', '视觉创意'],
    url: 'https://www.midjourney.com/',
    rating: 96,
    pricing: '付费',
    chinaReady: false,
    hot: true,
    scenario: '品牌视觉、海报概念、内容配图',
  },
  {
    id: 'jimeng',
    name: '即梦 AI',
    description: '字节系图像和视频创作工具，适合短视频素材和视觉内容生成。',
    category: 'AI视频',
    tags: ['国内可用', '图像', '视频', '短视频'],
    url: 'https://jimeng.jianying.com/',
    rating: 94,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '短视频素材、社媒视觉、内容生成',
  },
  {
    id: 'kling',
    name: '可灵 AI',
    description: '快手推出的 AI 视频生成工具，支持图生视频和创意短片。',
    category: 'AI视频',
    tags: ['国内可用', '视频生成', '图生视频'],
    url: 'https://klingai.kuaishou.com/',
    rating: 94,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '广告视频、产品展示、短视频创意',
  },
  {
    id: 'seedance',
    name: 'Seedance',
    description: '字节 Seed 团队视频生成模型相关产品入口，适合高质量视频生成研究。',
    category: 'AI视频',
    tags: ['视频模型', 'Seedance', '短视频'],
    url: 'https://www.seedance.tv/',
    rating: 92,
    pricing: '免费试用',
    chinaReady: false,
    latest: true,
    scenario: '视频模型评估、高质量短视频生成',
  },
  {
    id: 'runway',
    name: 'Runway',
    description: '专业 AI 视频创作平台，覆盖视频生成、编辑和创意工作流。',
    category: 'AI视频',
    tags: ['视频生成', '视频编辑', '创意工作流'],
    url: 'https://runwayml.com/',
    rating: 95,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '品牌视频、创意广告、素材编辑',
  },
  {
    id: 'pika',
    name: 'Pika',
    description: 'AI 视频生成与创意动效工具，适合轻量视频和社媒内容。',
    category: 'AI视频',
    tags: ['视频生成', '动效', '社媒'],
    url: 'https://pika.art/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '轻量视频、动态内容、社媒素材',
  },
  {
    id: 'liblib',
    name: 'LiblibAI',
    description: '国内 AI 图像和视频创作平台，覆盖模型、工作流和在线生成。',
    category: 'AI图像',
    tags: ['国内可用', '模型社区', '图像', '视频'],
    url: 'https://www.liblib.art/',
    rating: 90,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    scenario: '模型素材、图像生成、工作流调试',
  },
  {
    id: 'gaoding',
    name: '稿定 AI',
    description: '在线设计与 AI 图片工具，适合营销图、海报和电商图片。',
    category: 'AI设计',
    tags: ['国内可用', '设计', '海报', '电商图'],
    url: 'https://www.gaoding.com/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '营销海报、电商主图、社媒配图',
  },
  {
    id: 'meitu-design',
    name: '美图设计室',
    description: '美图旗下在线设计平台，提供 AI 图片创作和商业设计能力。',
    category: 'AI设计',
    tags: ['国内可用', '设计', '图片', '营销'],
    url: 'https://www.designkit.cn/',
    rating: 87,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '营销物料、图片优化、品牌视觉',
  },
  {
    id: 'canva',
    name: 'Canva',
    description: '在线设计平台，集成多种 AI 设计、文案和素材能力。',
    category: 'AI设计',
    tags: ['设计', '模板', '海报', '演示'],
    url: 'https://www.canva.com/',
    rating: 90,
    pricing: '免费试用',
    chinaReady: false,
    business: true,
    scenario: '社媒图、演示稿、品牌设计',
  },
  {
    id: 'gamma',
    name: 'Gamma',
    description: 'AI 演示文稿和网页式文档生成工具，适合快速制作方案。',
    category: 'AI办公',
    tags: ['PPT', '演示', '文档', '方案'],
    url: 'https://gamma.app/',
    rating: 93,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '商业方案、课程课件、路演材料',
  },
  {
    id: 'aippt',
    name: 'AiPPT',
    description: '中文 AI PPT 生成工具，适合快速生成办公演示稿。',
    category: 'AI办公',
    tags: ['国内可用', 'PPT', '演示', '办公'],
    url: 'https://www.aippt.cn/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '企业汇报、销售方案、培训课件',
  },
  {
    id: 'xunfei-zhiwen',
    name: '讯飞智文',
    description: '科大讯飞推出的文档和 PPT 生成工具，面向中文办公场景。',
    category: 'AI办公',
    tags: ['国内可用', 'PPT', 'Word', '办公'],
    url: 'https://zhiwen.xfyun.cn/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '文档初稿、PPT 生成、办公材料',
  },
  {
    id: 'baidu-wenku-ai',
    name: '百度文库 AI',
    description: '百度文库的一站式智能文档助手，适合资料和办公文档处理。',
    category: 'AI办公',
    tags: ['国内可用', '文档', '资料', '办公'],
    url: 'https://wenku.baidu.com/',
    rating: 85,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '文档生成、资料整理、模板检索',
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: '集成在 Notion 中的 AI 写作、总结和知识库助手。',
    category: 'AI办公',
    tags: ['知识库', '文档', '写作', '协作'],
    url: 'https://www.notion.com/product/ai',
    rating: 88,
    pricing: '付费',
    chinaReady: false,
    business: true,
    scenario: '团队知识库、项目文档、会议总结',
  },
  {
    id: 'biling',
    name: '笔灵 AI',
    description: '中文写作工具，覆盖论文、公文、新媒体和商业文案。',
    category: 'AI写作',
    tags: ['国内可用', '写作', '论文', '文案'],
    url: 'https://ibiling.cn/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '论文初稿、公文写作、新媒体文案',
  },
  {
    id: 'miaobi',
    name: '新华妙笔',
    description: '面向中文公文和正式写作场景的 AI 写作工具。',
    category: 'AI写作',
    tags: ['国内可用', '公文', '正式写作'],
    url: 'https://miaobi.xinhuaskl.com/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '公文材料、正式汇报、体制内写作',
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    description: '营销文案和销售内容生成平台，适合海外增长团队。',
    category: 'AI写作',
    tags: ['营销文案', '销售', '英文'],
    url: 'https://www.copy.ai/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '英文广告文案、邮件、销售话术',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI 编程 IDE，适合代码生成、重构、问答和项目开发。',
    category: 'AI编程',
    tags: ['IDE', '代码', '开发', 'Agent'],
    url: 'https://cursor.com/',
    rating: 95,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '软件开发、代码维护、原型实现',
  },
  {
    id: 'trae',
    name: 'TRAE',
    description: '字节推出的 AI 编程工具，面向智能编码和协作开发。',
    category: 'AI编程',
    tags: ['国内可用', 'IDE', '代码', '编程'],
    url: 'https://www.trae.ai/',
    rating: 89,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    scenario: '代码生成、项目开发、工程辅助',
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Anthropic 面向终端和代码库的 Agent 编程工具。',
    category: 'AI编程',
    tags: ['代码', 'Agent', '终端', '自动化'],
    url: 'https://www.anthropic.com/claude-code',
    rating: 92,
    pricing: '付费',
    chinaReady: false,
    latest: true,
    scenario: '复杂代码库维护、自动化开发任务',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'GitHub 官方 AI 编程助手，适合主流 IDE 中的代码补全和问答。',
    category: 'AI编程',
    tags: ['代码补全', 'IDE', 'GitHub'],
    url: 'https://github.com/features/copilot',
    rating: 90,
    pricing: '付费',
    chinaReady: false,
    business: true,
    scenario: '日常开发、代码补全、测试辅助',
  },
  {
    id: 'dify',
    name: 'Dify',
    description: '开源 LLM 应用开发平台，适合搭建工作流、知识库和智能体。',
    category: 'AI开发平台',
    tags: ['开源', '工作流', '知识库', 'Agent'],
    url: 'https://dify.ai/',
    rating: 92,
    pricing: '开源',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '企业 AI 应用、客服机器人、知识库问答',
  },
  {
    id: 'coze',
    name: '扣子 Coze',
    description: '字节推出的 AI Bot 和智能体开发平台，适合快速搭建业务机器人。',
    category: 'AI智能体',
    tags: ['国内可用', 'Bot', 'Agent', '工作流'],
    url: 'https://www.coze.cn/',
    rating: 91,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '客服机器人、内容助手、业务自动化',
  },
  {
    id: 'coze-global',
    name: 'Coze',
    description: '海外版智能体开发平台，支持 Bot、插件和工作流编排。',
    category: 'AI智能体',
    tags: ['Agent', 'Bot', '工作流'],
    url: 'https://www.coze.com/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '海外智能体、跨平台 Bot、原型验证',
  },
  {
    id: 'flowith',
    name: 'Flowith',
    description: '面向复杂任务的 AI 工作空间和 Agent 画布。',
    category: 'AI智能体',
    tags: ['Agent', '画布', '研究', '工作流'],
    url: 'https://flowith.io/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: false,
    latest: true,
    scenario: '复杂任务拆解、多步骤研究、Agent 编排',
  },
  {
    id: 'zapier-ai',
    name: 'Zapier AI',
    description: '自动化平台中的 AI 能力，适合连接 SaaS 工具和业务流程。',
    category: 'AI智能体',
    tags: ['自动化', 'SaaS', '工作流'],
    url: 'https://zapier.com/ai',
    rating: 86,
    pricing: '免费试用',
    chinaReady: false,
    business: true,
    scenario: '跨系统自动化、通知流、数据同步',
  },
  {
    id: 'make',
    name: 'Make',
    description: '可视化自动化平台，支持集成 AI 和第三方工具流程。',
    category: 'AI智能体',
    tags: ['自动化', '工作流', '集成'],
    url: 'https://www.make.com/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '业务流程自动化、跨工具数据流',
  },
  {
    id: 'suno',
    name: 'Suno',
    description: 'AI 音乐生成工具，适合歌曲、背景音乐和创意音频。',
    category: 'AI音频',
    tags: ['音乐', '歌曲', '音频生成'],
    url: 'https://suno.com/',
    rating: 92,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    scenario: '短视频 BGM、品牌音乐、创意歌曲',
  },
  {
    id: 'udio',
    name: 'Udio',
    description: 'AI 音乐创作平台，适合生成完整歌曲和音乐片段。',
    category: 'AI音频',
    tags: ['音乐', '歌曲', '音频'],
    url: 'https://www.udio.com/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '音乐创作、视频配乐、广告音频',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: '高质量 AI 语音生成和声音克隆平台。',
    category: 'AI音频',
    tags: ['TTS', '配音', '声音克隆'],
    url: 'https://elevenlabs.io/',
    rating: 93,
    pricing: '免费试用',
    chinaReady: false,
    hot: true,
    business: true,
    scenario: '视频配音、英文旁白、客服语音',
  },
  {
    id: 'murf',
    name: 'Murf',
    description: 'AI 配音工具，适合营销视频、课程和企业旁白。',
    category: 'AI音频',
    tags: ['配音', 'TTS', '营销视频'],
    url: 'https://murf.ai/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: false,
    scenario: '产品视频配音、课程旁白、企业介绍',
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'AI 数字人视频平台，适合口播、翻译和营销视频。',
    category: 'AI视频',
    tags: ['数字人', '口播', '翻译', '视频'],
    url: 'https://www.heygen.com/',
    rating: 91,
    pricing: '免费试用',
    chinaReady: false,
    business: true,
    scenario: '数字人口播、海外营销、本地化视频',
  },
  {
    id: 'youyan',
    name: '有言',
    description: '一站式 AI 视频创作和 3D 数字人生成平台。',
    category: 'AI视频',
    tags: ['国内可用', '数字人', '视频', '口播'],
    url: 'https://www.youyan3d.com/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '数字人短视频、企业宣传、培训口播',
  },
  {
    id: 'chanjing',
    name: '蝉镜',
    description: 'AI 数字人视频生成平台，适合直播切片和口播内容。',
    category: 'AI视频',
    tags: ['国内可用', '数字人', '口播'],
    url: 'https://www.chanjing.cc/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '数字人带货、营销口播、短视频矩阵',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: '国产通用大模型助手，擅长推理、代码、数学和中文问答。',
    category: 'AI聊天',
    tags: ['国内可用', '推理', '代码', '通用助手'],
    url: 'https://chat.deepseek.com/',
    rating: 97,
    pricing: '免费',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '复杂推理、代码辅助、企业知识问答',
  },
  {
    id: 'yuanbao',
    name: '腾讯元宝',
    description: '腾讯推出的 AI 助手，适合微信生态资料理解、写作和搜索。',
    category: 'AI聊天',
    tags: ['国内可用', '腾讯', '搜索', '写作'],
    url: 'https://yuanbao.tencent.com/',
    rating: 93,
    pricing: '免费',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '微信生态资料处理、中文问答、办公写作',
  },
  {
    id: 'wenxin',
    name: '文心一言',
    description: '百度推出的中文 AI 助手，覆盖写作、问答、图片和办公场景。',
    category: 'AI聊天',
    tags: ['国内可用', '百度', '写作', '问答'],
    url: 'https://yiyan.baidu.com/',
    rating: 90,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '中文写作、知识问答、办公材料生成',
  },
  {
    id: 'zhipu-qingyan',
    name: '智谱清言',
    description: '智谱 AI 推出的国产 AI 助手，适合问答、写作和多模态任务。',
    category: 'AI聊天',
    tags: ['国内可用', '智谱', '多模态', '写作'],
    url: 'https://chatglm.cn/',
    rating: 89,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '中文问答、文案生成、知识整理',
  },
  {
    id: 'sparkdesk',
    name: '讯飞星火',
    description: '科大讯飞推出的认知大模型助手，适合办公、教育和中文表达。',
    category: 'AI聊天',
    tags: ['国内可用', '讯飞', '办公', '教育'],
    url: 'https://xinghuo.xfyun.cn/',
    rating: 89,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '中文办公、教育资料、语音和文档处理',
  },
  {
    id: 'nami-ai',
    name: '纳米AI',
    description: '面向搜索、报告、PPT 和多智能体任务的国产 AI 工作台。',
    category: 'AI搜索',
    tags: ['国内可用', '搜索', '报告', 'PPT', '智能体'],
    url: 'https://www.n.cn/',
    rating: 94,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    latest: true,
    business: true,
    scenario: '行业调研、报告生成、PPT 初稿和复杂搜索',
  },
  {
    id: 'baidu-ai-search',
    name: '百度AI搜索',
    description: '百度推出的 AI 搜索入口，适合复杂问题搜索和资料整合。',
    category: 'AI搜索',
    tags: ['国内可用', '百度', '搜索', '资料整理'],
    url: 'https://chat.baidu.com/',
    rating: 90,
    pricing: '免费',
    chinaReady: true,
    business: true,
    scenario: '中文搜索、行业资料、学习和办公查询',
  },
  {
    id: 'quark-ai',
    name: '夸克AI',
    description: '夸克推出的 AI 搜索和学习办公助手，覆盖资料、文档和创作。',
    category: 'AI搜索',
    tags: ['国内可用', '搜索', '学习', '文档'],
    url: 'https://www.quark.cn/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '资料搜索、学习辅助、文档处理',
  },
  {
    id: 'wps-ai',
    name: 'WPS AI',
    description: '金山办公推出的 AI 办公助手，深度覆盖文档、表格和演示。',
    category: 'AI办公',
    tags: ['国内可用', 'WPS', '文档', '表格', 'PPT'],
    url: 'https://ai.wps.cn/',
    rating: 92,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '企业文档、表格分析、PPT 和办公协作',
  },
  {
    id: 'qingzhu-ppt',
    name: '轻竹办公',
    description: '面向国内用户的 AI PPT 和办公内容生成工具。',
    category: 'AI办公',
    tags: ['国内可用', 'PPT', '办公', '模板'],
    url: 'https://qingzhuai.com/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '汇报 PPT、课程课件、中文办公演示',
  },
  {
    id: 'bigeppt',
    name: '笔格PPT',
    description: 'AI 一键生成 PPT 工具，适合职场汇报和学生演示。',
    category: 'AI办公',
    tags: ['国内可用', 'PPT', '模板', '汇报'],
    url: 'https://www.bigeppt.com/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '工作汇报、项目展示、课程演示',
  },
  {
    id: 'mindshow',
    name: '麦当秀 MindShow',
    description: '在线 AI PPT 和演示制作工具，适合快速生成展示材料。',
    category: 'AI办公',
    tags: ['国内可用', 'PPT', '演示', '模板'],
    url: 'https://www.mindshow.fun/',
    rating: 83,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '演示稿生成、培训材料、方案展示',
  },
  {
    id: 'wanxing-zhiyan',
    name: '万兴智演',
    description: '万兴科技推出的 AI PPT 和演示视频制作工具。',
    category: 'AI办公',
    tags: ['国内可用', 'PPT', '演示', '视频'],
    url: 'https://zhiyan.wondershare.cn/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '企业演示、产品介绍、培训课件',
  },
  {
    id: 'tongyi-wanxiang',
    name: '通义万相',
    description: '阿里推出的 AI 创意图像平台，适合图片生成和视觉创作。',
    category: 'AI图像',
    tags: ['国内可用', '阿里', '生图', '创意视觉'],
    url: 'https://tongyi.aliyun.com/wanxiang/',
    rating: 90,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '营销配图、创意图片、商品视觉',
  },
  {
    id: 'wenxin-yige',
    name: '文心一格',
    description: '百度推出的 AI 艺术和图像创作平台。',
    category: 'AI图像',
    tags: ['国内可用', '百度', '生图', '艺术'],
    url: 'https://yige.baidu.com/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '插画、艺术图、营销视觉草稿',
  },
  {
    id: 'd-design',
    name: '堆友',
    description: '阿里旗下设计社区和 AI 创作工具，覆盖图像、视频和设计素材。',
    category: 'AI设计',
    tags: ['国内可用', '设计', '素材', '图像视频'],
    url: 'https://d.design/',
    rating: 88,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    scenario: '设计灵感、AI 图片、短视频素材',
  },
  {
    id: 'huiwa-ai',
    name: '绘蛙AI',
    description: '面向电商营销的 AI 商品图和内容创作工具。',
    category: 'AI图像',
    tags: ['国内可用', '电商', '商品图', '营销'],
    url: 'https://www.ihuiwa.com/',
    rating: 87,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '电商主图、商品卖点图、营销素材',
  },
  {
    id: 'tusiart',
    name: '吐司AI',
    description: '国内 AI 绘画模型社区和在线生图平台。',
    category: 'AI图像',
    tags: ['国内可用', '模型社区', '生图', '绘画'],
    url: 'https://tusiart.com/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '模型查找、AI 绘画、风格图生成',
  },
  {
    id: 'miaohua',
    name: '秒画',
    description: '商汤科技推出的 AI 作画和图片生成平台。',
    category: 'AI图像',
    tags: ['国内可用', '生图', '插画', '商汤'],
    url: 'https://miaohua.sensetime.com/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '图片创意、插画生成、视觉草稿',
  },
  {
    id: 'whee',
    name: 'WHEE',
    description: '美图推出的 AI 图片和绘画创作工具。',
    category: 'AI图像',
    tags: ['国内可用', '美图', '生图', '修图'],
    url: 'https://www.whee.com/',
    rating: 84,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '图片创作、修图、美化和视觉内容',
  },
  {
    id: 'zaodian-ai',
    name: '造点AI',
    description: '夸克团队推出的 AI 图像与视频创作平台。',
    category: 'AI视频',
    tags: ['国内可用', '图像', '视频', '创意'],
    url: 'https://www.zaodianai.com/',
    rating: 85,
    pricing: '免费试用',
    chinaReady: true,
    latest: true,
    scenario: '短视频素材、创意图片、社媒内容',
  },
  {
    id: 'katu-ai',
    name: '咖图AI',
    description: 'AI 图像设计和创作工具，适合商业图片与内容设计。',
    category: 'AI设计',
    tags: ['国内可用', '设计', '生图', '商业图片'],
    url: 'https://www.katuai.com/',
    rating: 83,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '商品图、海报、商业配图',
  },
  {
    id: 'baitianmeng',
    name: '白日梦',
    description: 'AI 视频创作平台，适合故事视频、短片和内容生成。',
    category: 'AI视频',
    tags: ['国内可用', '视频生成', '故事视频'],
    url: 'https://aibrm.com/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    scenario: '短剧素材、故事视频、创意短片',
  },
  {
    id: 'libtv',
    name: 'LibTV',
    description: '专业 AI 视频创作平台，支持 Seedance 等视频能力。',
    category: 'AI视频',
    tags: ['国内可用', '视频生成', 'Seedance'],
    url: 'https://www.libtv.cn/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    latest: true,
    business: true,
    scenario: '专业视频创作、广告素材、真人参考视频',
  },
  {
    id: 'vidu',
    name: 'Vidu',
    description: '生数科技推出的 AI 视频生成工具，适合创意短视频。',
    category: 'AI视频',
    tags: ['国内可用', '视频生成', '短视频'],
    url: 'https://www.vidu.cn/',
    rating: 87,
    pricing: '免费试用',
    chinaReady: true,
    hot: true,
    scenario: '图生视频、创意短片、社媒素材',
  },
  {
    id: 'lingma',
    name: '通义灵码 / Qoder CN',
    description: '阿里云智能编码助手，支持代码生成、问答、多文件修改和编程智能体。',
    category: 'AI编程',
    tags: ['国内可用', '阿里云', 'IDE', '编程智能体'],
    url: 'https://lingma.aliyun.com/',
    rating: 93,
    pricing: '免费',
    chinaReady: true,
    hot: true,
    business: true,
    scenario: '国内团队研发、代码补全、多文件修改',
  },
  {
    id: 'codegeex',
    name: 'CodeGeeX',
    description: '智谱系 AI 编程助手，支持代码生成、补全、解释和翻译。',
    category: 'AI编程',
    tags: ['国内可用', '代码补全', '智谱', 'IDE'],
    url: 'https://codegeex.cn/',
    rating: 87,
    pricing: '免费',
    chinaReady: true,
    business: true,
    scenario: '代码补全、代码解释、日常开发辅助',
  },
  {
    id: 'codebuddy',
    name: 'CodeBuddy',
    description: '腾讯云推出的 AI 编程助手，覆盖开发问答、代码生成和腾讯生态。',
    category: 'AI编程',
    tags: ['国内可用', '腾讯', '编程', '代码生成'],
    url: 'https://copilot.tencent.com/',
    rating: 86,
    pricing: '免费试用',
    chinaReady: true,
    latest: true,
    scenario: '腾讯云生态开发、代码生成、研发辅助',
  },
  {
    id: 'baidu-comate',
    name: '百度 Comate',
    description: '百度智能代码助手，支持代码补全、问答和企业研发场景。',
    category: 'AI编程',
    tags: ['国内可用', '百度', '代码', '研发'],
    url: 'https://comate.baidu.com/',
    rating: 85,
    pricing: '免费试用',
    chinaReady: true,
    business: true,
    scenario: '企业研发辅助、代码问答、代码补全',
  },
  {
    id: 'bailian',
    name: '阿里云百炼',
    description: '阿里云大模型应用开发平台，适合企业构建模型应用和智能体。',
    category: 'AI开发平台',
    tags: ['国内可用', '阿里云', '模型平台', '智能体'],
    url: 'https://bailian.console.aliyun.com/',
    rating: 91,
    pricing: '付费',
    chinaReady: true,
    business: true,
    scenario: '企业模型应用、智能体、知识库和工作流',
  },
  {
    id: 'qianfan',
    name: '百度千帆',
    description: '百度智能云大模型平台，提供模型、应用开发和企业 AI 能力。',
    category: 'AI开发平台',
    tags: ['国内可用', '百度', '模型平台', '企业AI'],
    url: 'https://cloud.baidu.com/product/wenxinworkshop',
    rating: 89,
    pricing: '付费',
    chinaReady: true,
    business: true,
    scenario: '企业大模型接入、知识库、应用开发',
  },
  {
    id: 'modelscope',
    name: '魔搭 ModelScope',
    description: '国内模型社区和 AI 开发平台，适合模型查找、体验和部署。',
    category: 'AI开发平台',
    tags: ['国内可用', '模型社区', '开源', '部署'],
    url: 'https://www.modelscope.cn/',
    rating: 90,
    pricing: '开源',
    chinaReady: true,
    hot: true,
    scenario: '模型查找、开源模型体验、AI 原型开发',
  },
  {
    id: 'paddlepaddle',
    name: '飞桨 AI Studio',
    description: '百度飞桨 AI 学习和开发社区，提供模型、数据集和 Notebook。',
    category: 'AI开发平台',
    tags: ['国内可用', '飞桨', '模型', '学习'],
    url: 'https://aistudio.baidu.com/',
    rating: 84,
    pricing: '免费',
    chinaReady: true,
    scenario: 'AI 学习、模型训练、算法实验',
  },
]
